
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("视频帧提取器")
        MainWindow.resize(788, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(788, 590))
        MainWindow.setMaximumSize(QtCore.QSize(788, 590))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 771, 431))
        self.groupBox.setMinimumSize(QtCore.QSize(771, 431))
        self.groupBox.setObjectName("groupBox")
        self.tableWidget_lists = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_lists.setGeometry(QtCore.QRect(10, 40, 751, 381))
        self.tableWidget_lists.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_lists.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget_lists.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget_lists.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget_lists.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget_lists.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_lists.setCornerButtonEnabled(True)
        self.tableWidget_lists.setObjectName("tableWidget_lists")
        self.tableWidget_lists.setColumnCount(5)
        self.tableWidget_lists.setRowCount(0)
        self.tableWidget_lists.setColumnWidth(0, 245)
        self.tableWidget_lists.setColumnWidth(1, 245)
        self.tableWidget_lists.setColumnWidth(2, 55)
        self.tableWidget_lists.setColumnWidth(3, 100)
        self.tableWidget_lists.setColumnWidth(4, 50)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lists.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lists.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lists.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lists.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_lists.setHorizontalHeaderItem(4, item)
        self.button_piclayer_open = QtWidgets.QToolButton(self.groupBox)
        self.button_piclayer_open.setGeometry(QtCore.QRect(82, 16, 67, 18))
        self.button_piclayer_open.setObjectName("button_piclayer_open")

        self.button_delfiles = QtWidgets.QToolButton(self.groupBox)
        self.button_delfiles.setGeometry(QtCore.QRect(597, 16, 91, 18))
        self.button_delfiles.setObjectName("button_delfiles")
        self.button_clear = QtWidgets.QToolButton(self.groupBox)
        self.button_clear.setGeometry(QtCore.QRect(694, 16, 67, 18))
        self.button_clear.setObjectName("button_clear")
        #self.button_addpath = QtWidgets.QToolButton(self.groupBox)
        #self.button_addpath.setGeometry(QtCore.QRect(83, 16, 91, 18))
        #self.button_addpath.setObjectName("button_addpath")
        self.button_addfile = QtWidgets.QToolButton(self.groupBox)
        self.button_addfile.setGeometry(QtCore.QRect(10, 16, 67, 18))
        self.button_addfile.setObjectName("button_addfile")
        self.label_format = QtWidgets.QLabel(self.groupBox)
        self.label_format.setGeometry(QtCore.QRect(165, 19, 54, 12))
        self.label_format.setObjectName("label_format")
        self.radioButton_png = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_png.setGeometry(QtCore.QRect(222, 17, 41, 16))
        self.radioButton_png.setObjectName("radioButton_png")
        self.radioButton_jpg = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_jpg.setGeometry(QtCore.QRect(266, 17, 41, 16))
        self.radioButton_jpg.setObjectName("radioButton_jpg")
        self.radioButton_jpg.setChecked(True)
        self.groupBox_hv = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_hv.setGeometry(QtCore.QRect(320, 22, 150, 24))
        self.groupBox_hv.setMinimumSize(QtCore.QSize(150, 24))
        self.groupBox_hv.setObjectName("groupBox_hv")
        self.groupBox_hv.setStyleSheet("border: 0px outset;")
        self.label_hv = QtWidgets.QLabel(self.groupBox_hv)
        self.label_hv.setGeometry(QtCore.QRect(10, 5, 65, 16))
        self.label_hv.setObjectName("label_hv")  # 封面图横竖
        self.radioButton_o_h = QtWidgets.QRadioButton(self.groupBox_hv)
        self.radioButton_o_h.setGeometry(QtCore.QRect(67, 5, 41, 16))
        self.radioButton_o_h.setObjectName("radioButton_o_h")
        self.radioButton_o_v = QtWidgets.QRadioButton(self.groupBox_hv)
        self.radioButton_o_v.setGeometry(QtCore.QRect(104, 5, 41, 16))
        self.radioButton_o_v.setObjectName("radioButton_o_v")
        self.radioButton_o_h.setChecked(True)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 440, 771, 51))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radio_getposter = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_getposter.setGeometry(QtCore.QRect(20, 19, 86, 16))
        self.radio_getposter.setObjectName("radio_getposter")
        self.radio_getframe_num = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_getframe_num.setGeometry(QtCore.QRect(142, 19, 86, 16))
        self.radio_getframe_num.setObjectName("radio_getframe_num")
        self.radio_getframe_random = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_getframe_random.setGeometry(QtCore.QRect(310, 19, 86, 16))
        self.radio_getframe_random.setChecked(True)
        self.radio_getframe_random.setObjectName("radio_getframe_random")
        self.line_limitTime1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_limitTime1.setGeometry(QtCore.QRect(402, 19, 51, 16))
        self.line_limitTime1.setMaxLength(6)
        self.line_limitTime1.setCursorPosition(0)
        self.line_limitTime1.setReadOnly(False)
        self.line_limitTime1.setObjectName("line_limitTime1")
        self.line_limitTime2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_limitTime2.setGeometry(QtCore.QRect(487, 19, 51, 16))
        self.line_limitTime2.setMaxLength(6)
        self.line_limitTime2.setReadOnly(False)
        self.line_limitTime2.setClearButtonEnabled(False)
        self.line_limitTime2.setObjectName("line_limitTime2")
        self.line_frame_random_num = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_frame_random_num.setGeometry(QtCore.QRect(682, 19, 41, 16))
        self.line_frame_random_num.setMaxLength(5)
        self.line_frame_random_num.setCursorPosition(0)
        self.line_frame_random_num.setObjectName("line_frame_random_num")
        self.line_frame_num = QtWidgets.QLineEdit(self.groupBox_2)
        self.line_frame_num.setGeometry(QtCore.QRect(212, 19, 61, 16))
        self.line_frame_num.setObjectName("line_frame_num")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(630, 16, 108, 21))
        self.label_3.setObjectName("label_3")
        self.label_isLimitTime = QtWidgets.QLabel(self.groupBox_2)
        self.label_isLimitTime.setGeometry(QtCore.QRect(389, 19, 186, 16))
        self.label_isLimitTime.setObjectName("label_isLimitTime")
        self.button_confirm = QtWidgets.QToolButton(self.groupBox_2)
        self.button_confirm.setGeometry(QtCore.QRect(563, 19, 37, 16))
        self.button_confirm.setObjectName("button_confirm")
        self.radio_getposter.raise_()
        self.radio_getframe_num.raise_()
        self.radio_getframe_random.raise_()
        self.label_isLimitTime.raise_()
        self.line_limitTime1.raise_()
        self.line_limitTime2.raise_()
        self.line_frame_num.raise_()
        self.label_3.raise_()
        self.line_frame_random_num.raise_()
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 500, 621, 51))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.button_getOutPath = QtWidgets.QToolButton(self.groupBox_3)
        self.button_getOutPath.setGeometry(QtCore.QRect(470, 10, 41, 31))
        self.button_getOutPath.setObjectName("button_getOutPath")
        self.line_outPath = QtWidgets.QLineEdit(self.groupBox_3)
        self.line_outPath.setGeometry(QtCore.QRect(104, 10, 361, 31))
        self.line_outPath.setReadOnly(True)
        self.line_outPath.setPlaceholderText("./outImage")
        self.line_outPath.setObjectName("line_outPath")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(21, 19, 81, 16))
        self.label.setObjectName("label")
        self.button_openOutPath = QtWidgets.QToolButton(self.groupBox_3)
        self.button_openOutPath.setGeometry(QtCore.QRect(513, 10, 91, 31))
        self.button_openOutPath.setObjectName("button_openOutPath")
        self.button_start = QtWidgets.QToolButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(670, 500, 111, 51))
        self.button_start.setStyleSheet("font: 87 14pt;")
        self.button_start.setObjectName("button_start")
        self.button_stop = QtWidgets.QToolButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(670, 500, 111, 51))
        self.button_stop.setStyleSheet("font: 87 14pt;")
        self.button_stop.setObjectName("button_stop")
        self.button_stop.setHidden(True)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 560, 771, 21))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 560, 741, 18))
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("font: 8pt;background-color: rgba(255, 255, 255, 0); background-color: rgba(255, 255, 255, 0);")
        self.groupBox_4.raise_()
        self.textBrowser.raise_()
        self.toolButton = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton.setGeometry(QtCore.QRect(0, 0, 31, 19))
        self.toolButton.setObjectName("toolButton")
        self.toolButton.raise_()

        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 40, 751, 381))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableWidget_piclayer = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_piclayer.setGeometry(QtCore.QRect(310, 0, 441, 381))
        self.tableWidget_piclayer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_piclayer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_piclayer.horizontalHeader().setVisible(False)
        self.tableWidget_piclayer.verticalHeader().setVisible(False)
        self.tableWidget_piclayer.setAutoScroll(True)
        self.tableWidget_piclayer.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget_piclayer.setLineWidth(0)
        self.tableWidget_piclayer.setObjectName("tableWidget_piclayer")
        self.tableWidget_piclayer.setColumnCount(2)
        self.tableWidget_piclayer.setRowCount(0)
        self.tableWidget_piclayer.setColumnWidth(0, 210)
        self.tableWidget_piclayer.setColumnWidth(1, 210)
        self.toolButton_piclayer = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton_piclayer.setGeometry(QtCore.QRect(723, 0, 15, 15))
        self.toolButton_piclayer.setObjectName("toolButton_piclayer")
        self.tableWidget_piclist = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_piclist.setGeometry(QtCore.QRect(0, 0, 311, 381))
        self.tableWidget_piclist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_piclist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_piclist.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_piclist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_piclist.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget_piclist.setObjectName("tableWidget_piclist")
        self.tableWidget_piclist.setColumnCount(2)
        self.tableWidget_piclist.setRowCount(0)
        self.tableWidget_piclist.setColumnWidth(0, 242)
        self.tableWidget_piclist.setColumnWidth(1, 40)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_piclist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_piclist.setHorizontalHeaderItem(1, item)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_addfile, self.radioButton_png)
        MainWindow.setTabOrder(self.radioButton_png, self.radioButton_jpg)
        MainWindow.setTabOrder(self.radioButton_jpg, self.radioButton_o_h)
        MainWindow.setTabOrder(self.radioButton_o_h, self.radioButton_o_v)
        MainWindow.setTabOrder(self.radioButton_o_v, self.button_delfiles)
        # MainWindow.setTabOrder(self.button_addpath, self.button_delfiles)
        MainWindow.setTabOrder(self.button_delfiles, self.button_clear)
        MainWindow.setTabOrder(self.button_clear, self.tableWidget_lists)
        MainWindow.setTabOrder(self.tableWidget_lists, self.radio_getposter)
        MainWindow.setTabOrder(self.radio_getposter, self.radio_getframe_num)
        MainWindow.setTabOrder(self.radio_getframe_num, self.line_frame_num)
        MainWindow.setTabOrder(self.line_frame_num, self.radio_getframe_random)
        MainWindow.setTabOrder(self.radio_getframe_random, self.line_limitTime1)
        MainWindow.setTabOrder(self.line_limitTime1, self.line_limitTime2)
        MainWindow.setTabOrder(self.line_limitTime2, self.line_frame_random_num)
        MainWindow.setTabOrder(self.line_frame_random_num, self.line_outPath)
        MainWindow.setTabOrder(self.line_outPath, self.button_getOutPath)
        MainWindow.setTabOrder(self.button_getOutPath, self.button_openOutPath)
        MainWindow.setTabOrder(self.button_openOutPath, self.button_start)
        MainWindow.setTabOrder(self.button_start, self.button_stop)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "视频帧提取器v1.3"))
        self.groupBox.setTitle(_translate("MainWindow", "视频列表"))
        item = self.tableWidget_lists.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件"))
        item = self.tableWidget_lists.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "输出地址"))
        item = self.tableWidget_lists.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "帧数/时长"))
        item = self.tableWidget_lists.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "提取区间"))
        item = self.tableWidget_lists.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "状态"))
        self.button_delfiles.setText(_translate("MainWindow", "删除已选视频"))
        self.button_clear.setText(_translate("MainWindow", "清空表格"))
        #self.button_addpath.setText(_translate("MainWindow", "添加视频目录"))
        self.button_addfile.setText(_translate("MainWindow", "添加视频"))
        self.radio_getposter.setText(_translate("MainWindow", "提取封面图片"))
        self.radio_getframe_num.setText(_translate("MainWindow", "抽指定帧"))
        self.radio_getframe_random.setText(_translate("MainWindow", "随机抽帧"))
        self.line_limitTime1.setText(_translate("MainWindow", "0"))
        self.line_limitTime1.setPlaceholderText(_translate("MainWindow", "0"))
        self.line_limitTime2.setText(_translate("MainWindow", "100"))
        self.line_limitTime2.setPlaceholderText(_translate("MainWindow", "100"))
        self.line_frame_num.setText(_translate("MainWindow", "1"))
        self.line_frame_random_num.setText(_translate("MainWindow", "1"))
        self.line_frame_random_num.setPlaceholderText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "随机抽取        张"))
        self.label_isLimitTime.setText(_translate("MainWindow", "从         %帧到         %帧"))
        self.button_confirm.setText(_translate("MainWindow", "确认"))
        self.button_getOutPath.setText(_translate("MainWindow", "浏览"))
        self.line_outPath.setText(_translate("MainWindow", "./outImage"))
        self.label.setText(_translate("MainWindow", "图片保存地址："))
        self.button_openOutPath.setText(_translate("MainWindow", "打开文件夹"))
        self.button_start.setText(_translate("MainWindow", "开始提取"))
        self.button_stop.setText(_translate("MainWindow", "停止提取"))
        self.textBrowser.setText(_translate("MainWindow", "信息栏"))
        self.toolButton.setText(_translate("MainWindow", "打开"))
        self.radioButton_png.setText(_translate("MainWindow", "PNG"))
        self.radioButton_jpg.setText(_translate("MainWindow", "JPG"))
        self.radioButton_o_h.setText(_translate("MainWindow", "横"))
        self.radioButton_o_v.setText(_translate("MainWindow", "竖"))
        self.label_format.setText(_translate("MainWindow", "提取格式："))
        self.label_hv.setText(_translate("MainWindow", "封面版式："))
        self.toolButton_piclayer.setText(_translate("MainWindow", "X"))
        self.button_piclayer_open.setText(_translate("MainWindow", "图片处理"))
        item = self.tableWidget_piclist.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "视频文件"))
        item = self.tableWidget_piclist.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "图数"))


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(230, 120)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 80, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 61))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accepted)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.rejected)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "啥也不是"))

class Ui_Dialog_Log(object):
    def setupUi(self, Dialog_Log):
        Dialog_Log.setObjectName("Dialog_Log")
        Dialog_Log.resize(712, 365)
        self.textBrowser_log = QtWidgets.QTextBrowser(Dialog_Log)
        self.textBrowser_log.setGeometry(QtCore.QRect(10, 10, 691, 311))
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.textBrowser_log.setStyleSheet("font: 7pt;")
        self.toolButton_close = QtWidgets.QToolButton(Dialog_Log)
        self.toolButton_close.setGeometry(QtCore.QRect(370, 330, 90, 30))
        self.toolButton_close.setObjectName("toolButton_close")
        self.toolButton = QtWidgets.QToolButton(Dialog_Log)
        self.toolButton.setGeometry(QtCore.QRect(260, 330, 90, 30))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Dialog_Log)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Log)

    def retranslateUi(self, Dialog_Log):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Log.setWindowTitle(_translate("Dialog_Log", "Dialog"))
        self.toolButton_close.setText(_translate("Dialog_Log", "关闭"))
        self.toolButton.setText(_translate("Dialog_Log", "保存"))